spring:
  application:
    name: DDADNG

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

isens:
  auth-base-url: https://accounts.i-sens.com
  api-base-url: https://api.i-sens.com
  client-id: ${ISENS_CLIENT_ID}
  client-secret: ${ISENS_CLIENT_SECRET}
  redirect-uri: ${ISENS_REDIRECT_URI}
  scope: offline_access
